### ISSUE TITLE
Correct PEP8 and style

### ISSUE THREAD

**Issue by e5pecial** [e5pecial/twitter-sentiment#1]
This code so dirty

**Comment by spencerkee** [comment]
I want to take up this issue, at least for:

/sentiment/views.py
/sentiment/migrations/
/sentiment/algorythm/translit.py
/sentiment/algorythm/sentimentAnalyzer.py

Since those seem like the worst offenders/what I can do right now.

**Comment by e5pecial** [comment]
Hi! It's very cool that you decided to do it. Code is very old, dirty and miserable, but I hadn't any time to fix it
